#!/usr/bin/env bash
set -euo pipefail

# One-click: run all configs, validate trends, export report assets.
# Outputs:
#   - results/<RUN_ID>/... for each config
#   - results/report_master_<timestamp>.md (master index)
#
# Customize:
#   CONFIG_GLOB="configs/exp_*.yaml" bash scripts/one_click_report.sh
#   PYTHON_BIN=python3.11 bash scripts/one_click_report.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${ROOT_DIR}"

PYTHON_BIN="${PYTHON_BIN:-python3}"
CONFIG_GLOB="${CONFIG_GLOB:-configs/*.yaml}"
TS="$(date +%Y%m%d_%H%M%S)"

echo "============================================================"
echo "[one_click_report] ROOT_DIR=${ROOT_DIR}"
echo "[one_click_report] PYTHON_BIN=${PYTHON_BIN}"
echo "[one_click_report] CONFIG_GLOB=${CONFIG_GLOB}"
echo "[one_click_report] TS=${TS}"
echo "============================================================"
echo

# 1) venv
if [[ ! -d ".venv" ]]; then
  "${PYTHON_BIN}" -m venv .venv
fi
# shellcheck disable=SC1091
source .venv/bin/activate

python -V
python -m pip install --upgrade pip setuptools wheel
python -m pip install -r requirements.txt
python -m pip install -U pytest

# 2) tests
echo "------------------------------------------------------------"
echo "[one_click_report] pytest -q"
echo "------------------------------------------------------------"
pytest -q

# 3) prepare master output
MASTER="results/report_master_${TS}.md"
mkdir -p results
: > "${MASTER}"

echo "# Report master index (${TS})" >> "${MASTER}"
echo "" >> "${MASTER}"
echo "- Config glob: \`${CONFIG_GLOB}\`" >> "${MASTER}"
echo "- Generated by: scripts/one_click_report.sh" >> "${MASTER}"
echo "" >> "${MASTER}"

# 4) enumerate configs
shopt -s nullglob
CONFIGS=( ${CONFIG_GLOB} )
shopt -u nullglob

if [[ "${#CONFIGS[@]}" -eq 0 ]]; then
  echo "[one_click_report] No configs matched: ${CONFIG_GLOB}"
  exit 1
fi

echo "[one_click_report] Found ${#CONFIGS[@]} config(s)."
echo ""

FAIL=0

for cfg in "${CONFIGS[@]}"; do
  echo "------------------------------------------------------------"
  echo "[one_click_report] Config: ${cfg}"
  echo "------------------------------------------------------------"

  RUN_NAME="$(python - <<PY
import yaml
from pathlib import Path
p = Path("${cfg}")
d = yaml.safe_load(p.read_text())
print(d.get("project", {}).get("run_name", p.stem))
PY
)"
  RUN_ID="${RUN_NAME}_${TS}"
  RUN_DIR="results/${RUN_ID}"

  echo "[one_click_report] RUN_ID=${RUN_ID}"
  echo "[one_click_report] RUN_DIR=${RUN_DIR}"

  # Run experiment pipeline
  python -m src.run_all --config "${cfg}" --run_id "${RUN_ID}" | tee "results/log_${RUN_ID}.txt"

  # Validate trends
  if python scripts/validate_run.py "${RUN_DIR}" | tee "results/validate_${RUN_ID}.txt"; then
    echo "- ${cfg} => PASS  \`${RUN_DIR}\`" >> "${MASTER}"
  else
    echo "- ${cfg} => FAIL  \`${RUN_DIR}\`" >> "${MASTER}"
    FAIL=1
  fi

  # Export report assets
  python scripts/export_report_assets.py "${RUN_DIR}" | tee "results/export_${RUN_ID}.txt"

  echo "  - report snippet: \`${RUN_DIR}/report_assets/report_snippet.md\`" >> "${MASTER}"
  echo "  - key table: \`${RUN_DIR}/report_assets/table_key_points.md\`" >> "${MASTER}"
  echo "  - sla best table: \`${RUN_DIR}/report_assets/table_sla_best.md\`" >> "${MASTER}"
  echo "  - figures list: \`${RUN_DIR}/report_assets/figures_list.md\`" >> "${MASTER}"
  echo "" >> "${MASTER}"
done

echo "------------------------------------------------------------"
echo "[one_click_report] MASTER = ${MASTER}"
echo "------------------------------------------------------------"

if [[ "${FAIL}" -eq 1 ]]; then
  echo "[one_click_report] DONE with FAILURES (check validate logs)."
  exit 1
fi

echo "[one_click_report] DONE (all PASS)."
exit 0
